# coding: utf-8
source 'https://github.com/CocoaPods/Specs.git'

platform :ios


target 'MNNKitDemo' do
  project './MNNKitDemo.xcodeproj'
  
    platform :ios, '8.0'
    
    # 人脸检测
    pod 'MNNFaceDetection', '~> 0.0.1'
    # 手势识别
    pod 'MNNHandGestureDetection', '~> 0.0.1'
    # 人像分割
    pod 'MNNPortraitSegmentation', '~> 0.0.1'
    
    
#    pod 'MNNKitCore', :path=>"/Users/tsia/Documents/MNN/MNNKitWorkspace/MNNKitCore"
#    
#    
#    pod 'MNNFaceDetection', :path=>"/Users/tsia/Documents/MNN/MNNKitWorkspace/MNNFaceDetection"
#    
#    pod 'MNNPortraitSegmentation', :path=>"/Users/tsia/Documents/MNN/MNNKitWorkspace/MNNPortraitSegmentation"
#    
#    pod 'MNNHandGestureDetection', :path=>"/Users/tsia/Documents/MNN/MNNKitWorkspace/MNNHandGestureDetection"

    

    
end
